# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MbasedScore_S1_Ui.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(480, 640)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 60, 151, 51))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 120, 111, 41))
        self.label_2.setObjectName("label_2")
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(130, 120, 321, 31))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_2.setGeometry(QtCore.QRect(130, 190, 121, 31))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 190, 111, 41))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(260, 190, 111, 41))
        self.label_4.setObjectName("label_4")
        self.textBrowser_3 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_3.setGeometry(QtCore.QRect(340, 190, 111, 31))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(20, 280, 181, 31))
        self.label_5.setObjectName("label_5")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(130, 280, 321, 26))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(Dialog)
        self.comboBox_2.setGeometry(QtCore.QRect(133, 320, 111, 26))
        self.comboBox_2.setObjectName("comboBox_2")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(Dialog)
        self.commandLinkButton.setGeometry(QtCore.QRect(340, 600, 131, 41))
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.label_cname = QtWidgets.QLabel(Dialog)
        self.label_cname.setGeometry(QtCore.QRect(20, 50, 131, 16))
        self.label_cname.setObjectName("label_cname")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit.setGeometry(QtCore.QRect(130, 490, 101, 21))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(20, 370, 271, 31))
        self.label_6.setObjectName("label_6")
        self.comboBox_3 = QtWidgets.QComboBox(Dialog)
        self.comboBox_3.setGeometry(QtCore.QRect(290, 370, 161, 26))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(20, 420, 381, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(20, 440, 381, 61))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(240, 490, 141, 16))
        self.label_9.setObjectName("label_9")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 71, 41))
        self.pushButton.setObjectName("pushButton")
        self.label_8.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.textBrowser.raise_()
        self.textBrowser_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.textBrowser_3.raise_()
        self.label_5.raise_()
        self.comboBox.raise_()
        self.comboBox_2.raise_()
        self.commandLinkButton.raise_()
        self.label_cname.raise_()
        self.plainTextEdit.raise_()
        self.label_6.raise_()
        self.comboBox_3.raise_()
        self.label_7.raise_()
        self.label_9.raise_()
        self.pushButton.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Step 1: Setup Settings"))
        self.label_2.setText(_translate("Dialog", "Course Title:"))
        self.label_3.setText(_translate("Dialog", "Course Code:"))
        self.label_4.setText(_translate("Dialog", "Session No."))
        self.label_5.setText(_translate("Dialog", "Score File Type"))
        self.comboBox.setItemText(0, _translate("Dialog", "Continuous Assessment Score File"))
        self.comboBox.setItemText(1, _translate("Dialog", "Final Exam Score File"))
        self.commandLinkButton.setText(_translate("Dialog", "Next Step"))
        self.label_cname.setText(_translate("Dialog", "Course Name"))
        self.label_6.setText(_translate("Dialog", "Takes up 100% of the above Score Type"))
        self.comboBox_3.setItemText(0, _translate("Dialog", "Yes"))
        self.comboBox_3.setItemText(1, _translate("Dialog", "No"))
        self.label_7.setText(_translate("Dialog", "if no show this: "))
        self.label_8.setText(_translate("Dialog", "Please Specify the percentage "))
        self.label_9.setText(_translate("Dialog", "% of Total Score"))
        self.pushButton.setText(_translate("Dialog", "Return"))
