# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MbasedScore_S1_Ui.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(480, 640)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 40, 151, 51))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 190, 111, 41))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setEnabled(True)
        self.label_4.setGeometry(QtCore.QRect(240, 190, 111, 41))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(20, 280, 181, 31))
        self.label_5.setObjectName("label_5")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(130, 280, 321, 26))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(Dialog)
        self.comboBox_2.setGeometry(QtCore.QRect(133, 320, 321, 26))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(Dialog)
        self.commandLinkButton.setGeometry(QtCore.QRect(170, 580, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.commandLinkButton.setFont(font)
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.label_cname = QtWidgets.QLabel(Dialog)
        self.label_cname.setGeometry(QtCore.QRect(20, 100, 431, 16))
        self.label_cname.setObjectName("label_cname")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(20, 410, 271, 31))
        self.label_6.setObjectName("label_6")
        self.comboBox_3 = QtWidgets.QComboBox(Dialog)
        self.comboBox_3.setGeometry(QtCore.QRect(290, 410, 161, 26))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(20, 460, 381, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(20, 520, 381, 61))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(300, 540, 141, 16))
        self.label_9.setObjectName("label_9")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 171, 41))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(180, 540, 113, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setEnabled(False)
        self.lineEdit_2.setGeometry(QtCore.QRect(20, 140, 421, 21))
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_ccode = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_ccode.setEnabled(False)
        self.lineEdit_ccode.setGeometry(QtCore.QRect(120, 200, 113, 21))
        self.lineEdit_ccode.setReadOnly(True)
        self.lineEdit_ccode.setObjectName("lineEdit_ccode")
        self.lineEdit_sno = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_sno.setEnabled(False)
        self.lineEdit_sno.setGeometry(QtCore.QRect(320, 200, 121, 21))
        self.lineEdit_sno.setReadOnly(True)
        self.lineEdit_sno.setObjectName("lineEdit_sno")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 500, 161, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(180, 500, 111, 21))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(300, 500, 121, 16))
        self.label_10.setObjectName("label_10")
        self.label_8.raise_()
        self.label.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.comboBox.raise_()
        self.comboBox_2.raise_()
        self.commandLinkButton.raise_()
        self.label_cname.raise_()
        self.label_6.raise_()
        self.comboBox_3.raise_()
        self.label_7.raise_()
        self.label_9.raise_()
        self.pushButton.raise_()
        self.lineEdit.raise_()
        self.lineEdit_2.raise_()
        self.lineEdit_ccode.raise_()
        self.lineEdit_sno.raise_()
        self.label_2.raise_()
        self.lineEdit_3.raise_()
        self.label_10.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Step 1: Setup Settings"))
        self.label_3.setText(_translate("Dialog", "Course Code:"))
        self.label_4.setText(_translate("Dialog", "Session No."))
        self.label_5.setText(_translate("Dialog", "Score File Type"))
        self.comboBox.setItemText(0, _translate("Dialog", "Continuous Assessment Score File"))
        self.comboBox.setItemText(1, _translate("Dialog", "Final Exam Score File"))
        self.comboBox_2.setItemText(0, _translate("Dialog", "default value"))
        self.commandLinkButton.setText(_translate("Dialog", "Next Step"))
        self.label_cname.setText(_translate("Dialog", "Course Title"))
        self.label_6.setText(_translate("Dialog", "Takes up 100% of the above Score Type"))
        self.comboBox_3.setItemText(0, _translate("Dialog", "Yes"))
        self.comboBox_3.setItemText(1, _translate("Dialog", "No"))
        self.label_7.setText(_translate("Dialog", "if no show this: "))
        self.label_8.setText(_translate("Dialog", "Specify the percentage "))
        self.label_9.setText(_translate("Dialog", "% of Total Score"))
        self.pushButton.setText(_translate("Dialog", "Return to Score Panel"))
        self.label_2.setText(_translate("Dialog", "Name your Score type"))
        self.label_10.setText(_translate("Dialog", "e.g. Group Report"))
